### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by kitsuyui** [diogo464/sxd_html#1]
The contents of this repository are very useful. Please publish it on crates.io if possible.

I think it may need some work before it can be published.

- Add CI and other configurations
- Add a license
- Register on [crates.io](https://crates.io/) . 
- etc.

**Comment by kitsuyui** [comment]
@diogo464 

I have already forked over to https://github.com/kitsuyui/sxd_html to work on additional implementations. If you want to publish it on crates.io I can help you with that and send you some patches. Another option: if you are not interested in publishing, it may be possible to register my forked version on crates.io and I will update it.

In either case, the license issue would need to be resolved. MIT or Apache license seems to be a good fit. Other permissive licenses may also be acceptable.

c.f. https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive

What do you think?

**Comment by diogo464** [comment]
I don't mind publishing on crates.io, I am a bit busy with school right now but I can change the license and give you write access to the repo if you want to work on that.

**Comment by kitsuyui** [comment]
@diogo464

Thank you. I have prepared a pull request to add the license here for your review and merge. https://github.com/diogo464/sxd_html/pull/2

After having this merged, I would like to proceed with publishing to crates.io.

I will then add https://crates.io/users/diogo464 to Owner. That way, if in the future you want to take control of the project yourself, I can give it back to you.

**Comment by diogo464** [comment]
Ok, thanks. I accepted #2 and gave you write access. If you need anything else to publish on create.io just leave a message.

**Comment by kitsuyui** [comment]
@diogo464 
Thanks. I have just released first version on crates.io. I have also made an invite to give you owner privileges on this crate.
https://crates.io/crates/sxd_html
